apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-07-20T19:20:26Z"
  labels:
    app: hello-node
  name: hello-node
  namespace: default
  resourceVersion: "25660"
  uid: d03e181b-c39e-4a37-bc83-e699905dddee
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.67.225
  clusterIPs:
  - 10.104.67.225
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31171
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
